CREATE USER umair_readwrite WITH PASSWORD 'umairanwar';

GRANT USAGE, CREATE ON SCHEMA public TO umair_readwrite;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO umair_readwrite;

GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO umair_readwrite;

ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO umair_readwrite;
ALTER DEFAULT PRIVILEGES IN SCHEMA public 
    GRANT USAGE ON SEQUENCES TO umair_readwrite;